# Legacy ifupdown requires its own template, so we broke it out into a seperate
# role. In theory, ifupdown2 is capable of running on hosts, but it takes some
# work to install without having it conflict with other packages. For this demo,
# legacy ifupdown does what we need.

# This configures the interfaces and sets the default internal route to point
# to the leafs. If the configuration changes, ifupdown will be reloaded.
- name: configure /etc/network/interfaces on the host (using legacy ifupdown)
  template: src=interfaces.j2 dest=/etc/network/interfaces
  notify: reload networking legacy

- name: run the handler
  meta: flush_handlers

- name: force eth1 interface up
  command: ifup eth1

- name: force eth2 interface up
  command: ifup eth2

- name: Check if default for eth1/eth2 is installed
  shell: "ip route show"
  register: default_installed
  when: "'server' in ansible_hostname"

- name: Add 10.0.0.0/8 route if on server01
  lineinfile: dest=/etc/rc.local line="ip route add 10.0.0.0/8 nexthop via 10.0.0.11 dev eth1 onlink nexthop via 10.0.0.12 dev eth2 onlink" insertbefore="exit 0"
  when: "'server01' in ansible_hostname and 'nexthop via 10.0.0.11' not in default_installed.stdout"
 
- name: make sure 10.0.0.0/8 is present on server01
  command: ip route add 10.0.0.0/8 nexthop via 10.0.0.11 dev eth1 onlink nexthop via 10.0.0.12 dev eth2 onlink
  when: "'server01' in ansible_hostname and 'nexthop via 10.0.0.11' not in default_installed.stdout"
     
- name: Add 10.0.0.0/8 route if on server02
  lineinfile: dest=/etc/rc.local line="ip route add 10.0.0.0/8 nexthop via 10.0.0.11 dev eth1 onlink nexthop via 10.0.0.12 dev eth2 onlink" insertbefore="exit 0"
  when: "'server02' in ansible_hostname and 'nexthop via 10.0.0.11' not in default_installed.stdout"
 
- name: make sure 10.0.0.0/8 is present on server02
  command: ip route add 10.0.0.0/8 nexthop via 10.0.0.11 dev eth1 onlink nexthop via 10.0.0.12 dev eth2 onlink
  when: "'server02' in ansible_hostname and 'nexthop via 10.0.0.11' not in default_installed.stdout"

- name: Add 10.0.0.0/8 route if on server03
  lineinfile: dest=/etc/rc.local line="ip route add 10.0.0.0/8 nexthop via 10.0.0.13 dev eth1 onlink nexthop via 10.0.0.14 dev eth2 onlink" insertbefore="exit 0"
  when: "'server03' in ansible_hostname and 'nexthop via 10.0.0.13' not in default_installed.stdout"
 
- name: make sure 10.0.0.0/8 is present on server03
  command: ip route add 10.0.0.0/8 nexthop via 10.0.0.13 dev eth1 onlink nexthop via 10.0.0.14 dev eth2 onlink
  when: "'server03' in ansible_hostname and 'nexthop via 10.0.0.13' not in default_installed.stdout"

- name: Add 10.0.0.0/8 route if on server04
  lineinfile: dest=/etc/rc.local line="ip route add 10.0.0.0/8 nexthop via 10.0.0.13 dev eth1 onlink nexthop via 10.0.0.14 dev eth2 onlink" insertbefore="exit 0"
  when: "'server04' in ansible_hostname and 'nexthop via 10.0.0.13' not in default_installed.stdout"
 
- name: make sure 10.0.0.0/8 is present on server04
  command: ip route add 10.0.0.0/8 nexthop via 10.0.0.13 dev eth1 onlink nexthop via 10.0.0.14 dev eth2 onlink
  when: "'server04' in ansible_hostname and 'nexthop via 10.0.0.13' not in default_installed.stdout"