# One of the key tasks of automation are to install and configure services on
# servers. This example installs the ifplugd package and accompanying config 
# file on the servers.
- name: install ifplugd 
  apt: name=ifplugd update_cache=yes

# Push the ifplugd configuration file.
- name: Push ifplugd config
  copy: src=ifplugd dest=/etc/default/ifplugd

# If ifplugd is not running, this starts it. Automation can be used to force a
# a server into a consistent state - if apache crashed or stopped running for
# any reason, this playbook will attempt to get it running again. If it's already
# running, this step is skipped.
- name: run ifplugd 
  service: name=ifplugd state=started
